import * as anchor from "@coral-xyz/anchor";
import { Connection, PublicKey, ComputeBudgetProgram, Transaction } from "@solana/web3.js";
import idl from "./idl/onside.json";
import settlementSigs from "./settlementSigs.json";
import { RPC, ONSIDE_PROGRAM_ID, TXORACLE_PROGRAM_ID, SEED_AUTHORITY } from "./config";
import { decodeMarket, marketPhase, OnsideMarket, Position } from "./markets";

// Snapshot of each resolved market's settlement (resolve_market) tx, generated by
// client/src/dump-settlement-sigs.ts. Settlement is immutable, so a static map is always
// correct and lets the Proofs page + receipt link on-chain instantly — no RPC at load,
// no 429 storm. Newly-settled markets (not yet in the snapshot) fall back to a live lookup.
const SIG_SNAPSHOT: Record<string, string> = settlementSigs as Record<string, string>;

export const ONSIDE_ID = new PublicKey(ONSIDE_PROGRAM_ID);
export const TXORACLE_ID = new PublicKey(TXORACLE_PROGRAM_ID);

// Market account byte offsets: 8 disc, then authority(32) @8, market_id(8) @40, fixture_id(8) @48.
const AUTHORITY_OFFSET = 8;
const FIXTURE_ID_OFFSET = 48;
const bs58 = (b: Buffer) => anchor.utils.bytes.bs58.encode(b);

function dummyWallet(): any {
  return {
    publicKey: PublicKey.default,
    signTransaction: async (t: any) => t,
    signAllTransactions: async (t: any) => t,
  };
}

// Read across MULTIPLE devnet RPC endpoints. Every free public RPC rate-limits (429)
// per-IP-per-endpoint under sustained getProgramAccounts polling, so we ROTATE: when the
// primary is throttled, the next endpoint usually still serves. All point at the same
// devnet cluster (same program + accounts), so any of them returns identical data.
// Writes still go through the primary (walletProgram) — they need the user's wallet.
const READ_RPCS: string[] = [
  ...new Set([RPC, "https://solana-devnet.api.onfinality.io/public", "https://api.devnet.solana.com"]),
];

function makeReadProgram(rpc: string) {
  // disableRetryOnRateLimit: don't let web3.js spin its own 429 backoff on one endpoint —
  // fail fast so withRpc() rotates to the next endpoint immediately (that's our failover).
  const connection = new Connection(rpc, { commitment: "confirmed", disableRetryOnRateLimit: true });
  const provider = new anchor.AnchorProvider(connection, dummyWallet(), { commitment: "confirmed" });
  return new anchor.Program(idl as any, provider);
}

const READ_PROGRAMS = READ_RPCS.map(makeReadProgram);

export function readProgram() {
  return READ_PROGRAMS[0];
}

/** SOL balance in lamports, via the failover pool — so a throttled endpoint can't wedge
 *  the wallet balance display (or spin a 429 retry storm on a single connection). */
export async function fetchSolBalance(owner: PublicKey): Promise<number> {
  return withRpc((program) => program.provider.connection.getBalance(owner));
}

/** Run a read against the RPC pool, rotating endpoints on failure (429 / timeout) with
 *  backoff, so a single throttled endpoint never makes a match look empty. */
async function withRpc<T>(fn: (program: anchor.Program) => Promise<T>, tries = 4): Promise<T> {
  let last: any;
  for (let i = 0; i < tries; i++) {
    const program = READ_PROGRAMS[i % READ_PROGRAMS.length];
    try {
      return await fn(program);
    } catch (e) {
      last = e;
      await new Promise((r) => setTimeout(r, 350 * (i + 1)));
    }
  }
  throw last;
}

export function walletProgram(wallet: any) {
  const connection = new Connection(RPC, "confirmed");
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: "confirmed" });
  return new anchor.Program(idl as any, provider);
}

export function positionPda(market: PublicKey, owner: PublicKey) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("position"), market.toBuffer(), owner.toBuffer()],
    ONSIDE_ID
  )[0];
}

export async function placeParlay(
  wallet: any,
  stakeLamports: number,
  legs: { market: string; side: "yes" | "no" }[]
): Promise<string> {
  const res = await fetch("/api/parlay/quote", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ owner: wallet.publicKey.toBase58(), stakeLamports, legs }),
  });
  const quote = await res.json();
  if (!res.ok) throw new Error(quote.error || "Unable to place parlay");
  const tx = Transaction.from(Buffer.from(quote.transaction, "base64"));
  const signed = await wallet.signTransaction(tx);
  const connection = new Connection(RPC, "confirmed");
  const signature = await connection.sendRawTransaction(signed.serialize());
  await connection.confirmTransaction(signature, "confirmed");
  return signature;
}

const authorityFilter = () => ({
  memcmp: { offset: AUTHORITY_OFFSET, bytes: bs58(new PublicKey(SEED_AUTHORITY).toBuffer()) },
});

function priority(desc: string): number {
  const order = ["Over 0.5 goals", "Over 1.5 goals", "Over 2.5 goals"];
  const i = order.indexOf(desc);
  if (i >= 0) return i;
  if (desc.includes("to win")) return 3;
  if (desc.includes("to score")) return 4;
  if (desc.includes("corners")) return 5;
  if (desc.includes("yellow")) return 6;
  if (desc.includes("red card")) return 7;
  return 8;
}

const BATCH_WINDOW = 180; // seconds — markets from one seed share a creation time

/** Keep only the latest seed batch, deduped by outcome (re-seeding supersedes cleanly). */
function latestBatch(ms: OnsideMarket[]): OnsideMarket[] {
  if (!ms.length) return [];
  const maxCreated = Math.max(...ms.map((m) => m.createdAt));
  const recent = ms.filter((m) => m.createdAt >= maxCreated - BATCH_WINDOW);
  const byDesc = new Map<string, OnsideMarket>();
  for (const m of recent) {
    const cur = byDesc.get(m.description);
    if (!cur || m.createdAt > cur.createdAt) byDesc.set(m.description, m);
  }
  return [...byDesc.values()].sort(
    (a, b) => priority(a.description) - priority(b.description) || a.description.localeCompare(b.description)
  );
}

export async function fetchMarketsForFixture(fixtureId: number): Promise<OnsideMarket[]> {
  const fid = new anchor.BN(fixtureId).toArrayLike(Buffer, "le", 8);
  const all = await withRpc<any[]>((program) =>
    (program.account as any).market.all([authorityFilter(), { memcmp: { offset: FIXTURE_ID_OFFSET, bytes: bs58(fid) } }])
  );
  return latestBatch(all.map((x: any) => decodeMarket(x.publicKey.toBase58(), x.account)));
}

/** Distinct active markets per fixture (single scan, authority-scoped). */
export async function countMarkets(fixtureIds: number[]): Promise<Record<number, number>> {
  const all = await withRpc<any[]>((program) => (program.account as any).market.all([authorityFilter()]));
  const byFix: Record<number, OnsideMarket[]> = {};
  for (const x of all) {
    const m = decodeMarket(x.publicKey.toBase58(), x.account);
    (byFix[m.fixtureId] ||= []).push(m);
  }
  const out: Record<number, number> = {};
  for (const f of fixtureIds) out[f] = byFix[f] ? latestBatch(byFix[f]).length : 0;
  return out;
}

/** Open market batches grouped by fixture, including fixtures that have rotated out
 * of TxODDS's rolling snapshot. This powers reliable sportsbook discovery. */
export async function fetchTradableFixtures(): Promise<Record<number, { count: number; closeTs: number }>> {
  const all = await withRpc<any[]>((program) => (program.account as any).market.all([authorityFilter()]));
  const byFixture: Record<number, OnsideMarket[]> = {};
  for (const row of all) {
    const market = decodeMarket(row.publicKey.toBase58(), row.account);
    (byFixture[market.fixtureId] ||= []).push(market);
  }
  const result: Record<number, { count: number; closeTs: number }> = {};
  for (const [fixtureId, markets] of Object.entries(byFixture)) {
    const open = latestBatch(markets).filter((market) => marketPhase(market) === "open");
    if (open.length) result[Number(fixtureId)] = { count: open.length, closeTs: Math.min(...open.map((market) => market.closeTs)) };
  }
  return result;
}

export async function fetchPositions(
  owner: PublicKey,
  marketPubkeys: string[]
): Promise<Record<string, Position>> {
  if (!marketPubkeys.length) return {};
  const pdas = marketPubkeys.map((m) => positionPda(new PublicKey(m), owner));
  const accs = await withRpc<any[]>((program) => (program.account as any).position.fetchMultiple(pdas));
  const out: Record<string, Position> = {};
  accs.forEach((acc: any, i: number) => {
    if (acc)
      out[marketPubkeys[i]] = {
        market: marketPubkeys[i],
        yesAmount: Number(acc.yesAmount),
        noAmount: Number(acc.noAmount),
      };
  });
  return out;
}

/** Every position owned by `owner` across all markets (for the My-bets portfolio).
 *  Position layout: 8 disc + market(32) + owner(32) → owner at offset 40. */
export async function fetchAllPositions(owner: PublicKey): Promise<Position[]> {
  const all = await withRpc<any[]>((program) => (program.account as any).position.all([{ memcmp: { offset: 40, bytes: bs58(owner.toBuffer()) } }]));
  return all.map((x: any) => ({
    market: x.account.market.toBase58(),
    yesAmount: Number(x.account.yesAmount),
    noAmount: Number(x.account.noAmount),
  }));
}

export type ParlayTicket = {
  publicKey: string;
  fixtureId: number;
  stake: number;
  oddsBps: number;
  payout: number;
  status: "open" | "won" | "lost" | "claimed";
  createdAt: number;
  legs: { market: string; side: "yes" | "no" }[];
};

export async function fetchParlayTickets(owner: PublicKey): Promise<ParlayTicket[]> {
  const all = await withRpc<any[]>((program) => (program.account as any).parlayTicket.all([
    { memcmp: { offset: 40, bytes: bs58(owner.toBuffer()) } },
  ]));
  return all.map((row: any) => {
    const status = row.account.status;
    return {
      publicKey: row.publicKey.toBase58(),
      fixtureId: Number(row.account.fixtureId),
      stake: Number(row.account.stake),
      oddsBps: Number(row.account.oddsBps),
      payout: Number(row.account.payout),
      status: status.won ? "won" : status.lost ? "lost" : status.claimed ? "claimed" : "open",
      createdAt: Number(row.account.createdAt),
      legs: row.account.legs.map((leg: any) => ({
        market: leg.market.toBase58(),
        side: leg.side.yes ? "yes" : "no",
      })),
    } as ParlayTicket;
  });
}

/** Decode specific markets by pubkey — a position can reference a superseded batch. */
export async function fetchMarketsByPubkeys(pubkeys: string[]): Promise<Record<string, OnsideMarket>> {
  if (!pubkeys.length) return {};
  const accs = await withRpc<any[]>((program) => (program.account as any).market.fetchMultiple(pubkeys.map((p) => new PublicKey(p))));
  const out: Record<string, OnsideMarket> = {};
  accs.forEach((acc: any, i: number) => {
    if (acc) out[pubkeys[i]] = decodeMarket(pubkeys[i], acc);
  });
  return out;
}

/** All active markets across every fixture (latest batch per fixture) — for analytics. */
export async function fetchAllMarkets(): Promise<OnsideMarket[]> {
  const all = await withRpc<any[]>((program) => (program.account as any).market.all([authorityFilter()]));
  const byFix: Record<number, OnsideMarket[]> = {};
  for (const x of all) {
    const m = decodeMarket(x.publicKey.toBase58(), x.account);
    (byFix[m.fixtureId] ||= []).push(m);
  }
  return Object.values(byFix).flatMap((ms) => latestBatch(ms));
}

function toNodes(a: any[]) {
  return a.map((n: any) => ({ hash: n.hash, isRightSibling: n.isRightSibling }));
}

/** Permissionless settlement: fetch the live TxODDS proof for THIS market's fixture
 *  and stats, then prove it on-chain and resolve. Works for any fixture with data. */
export async function settleMarket(wallet: any, market: OnsideMarket): Promise<string> {
  const program = walletProgram(wallet);

  const params = new URLSearchParams({
    fixtureId: String(market.fixtureId),
    statKey: String(market.statAKey),
  });
  if (market.statBKey) params.set("statKey2", String(market.statBKey));
  const res = await fetch(`/api/proof?${params.toString()}`);
  const v = await res.json();
  if (!res.ok || !v?.summary) {
    throw new Error(v?.error || "Match data not available yet — settle after the relevant moment");
  }

  const ts = v.summary.updateStats.minTimestamp;
  const fixtureSummary = {
    fixtureId: new anchor.BN(v.summary.fixtureId),
    updateStats: {
      updateCount: v.summary.updateStats.updateCount,
      minTimestamp: new anchor.BN(v.summary.updateStats.minTimestamp),
      maxTimestamp: new anchor.BN(v.summary.updateStats.maxTimestamp),
    },
    eventsSubTreeRoot: v.summary.eventStatsSubTreeRoot,
  };
  const statA = {
    statToProve: { key: v.statToProve.key, value: v.statToProve.value, period: v.statToProve.period },
    eventStatRoot: v.eventStatRoot,
    statProof: toNodes(v.statProof),
  };
  const statB = market.statBKey
    ? {
        statToProve: { key: v.statToProve2.key, value: v.statToProve2.value, period: v.statToProve2.period },
        eventStatRoot: v.eventStatRoot,
        statProof: toNodes(v.statProof2),
      }
    : null;

  const epochDay = Math.floor(ts / 86400000);
  const rootsPda = PublicKey.findProgramAddressSync(
    [Buffer.from("daily_scores_roots"), new anchor.BN(epochDay).toArrayLike(Buffer, "le", 2)],
    TXORACLE_ID
  )[0];

  return await program.methods
    .resolveMarket(new anchor.BN(ts), fixtureSummary, toNodes(v.subTreeProof), toNodes(v.mainTreeProof), statA, statB)
    .accounts({
      market: new PublicKey(market.publicKey),
      dailyScoresMerkleRoots: rootsPda,
      txOracleProgram: TXORACLE_ID,
      resolver: wallet.publicKey,
    })
    .preInstructions([ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 })])
    .rpc();
}

/** Most recent on-chain signature touching this market — the settlement/activity tx,
 *  so the resolution receipt can link straight to Solana Explorer. Goes through the failover
 *  pool (rotates endpoints, fails fast on 429) rather than spinning one connection's retry. */
export async function fetchSettlementSig(marketPubkey: string): Promise<string | null> {
  if (SIG_SNAPSHOT[marketPubkey]) return SIG_SNAPSHOT[marketPubkey];
  try {
    const pk = new PublicKey(marketPubkey);
    const sigs = await withRpc((program) => program.provider.connection.getSignaturesForAddress(pk, { limit: 10 }));
    const ok = sigs.find((s) => !s.err) || sigs[0];
    return ok?.signature ?? null;
  } catch {
    return null;
  }
}

/** Resolve settlement sigs for many markets with a small concurrency cap. A page full of
 *  resolved markets would otherwise fire dozens of getSignaturesForAddress calls at once and
 *  trip every endpoint's rate limit; a 3-wide worker pool keeps them flowing without a 429
 *  storm. onResult fires per market so the UI can fill rows in progressively. */
export async function fetchSettlementSigs(
  marketPubkeys: string[],
  onResult?: (pubkey: string, sig: string | null) => void,
  concurrency = 3
): Promise<Record<string, string | null>> {
  const out: Record<string, string | null> = {};
  let i = 0;
  const worker = async () => {
    while (i < marketPubkeys.length) {
      const pk = marketPubkeys[i++];
      const sig = await fetchSettlementSig(pk);
      out[pk] = sig;
      onResult?.(pk, sig);
    }
  };
  await Promise.all(Array.from({ length: Math.min(concurrency, marketPubkeys.length) }, worker));
  return out;
}

export async function claimMarket(wallet: any, market: OnsideMarket): Promise<string> {
  const program = walletProgram(wallet);
  const marketPk = new PublicKey(market.publicKey);
  const pos = positionPda(marketPk, wallet.publicKey);
  return await program.methods
    .claim()
    .accounts({ market: marketPk, position: pos, owner: wallet.publicKey })
    .rpc();
}
